# Generated by Django 5.0.1 on 2024-01-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
