# Generated by Django 5.0.1 on 2024-01-30 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0003_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
