# Generated by Django 5.0.1 on 2024-01-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0004_archive_submit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
