# Generated by Django 5.0.1 on 2024-01-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0005_archive_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='text',
            new_name='edited_text',
        ),
        migrations.AddField(
            model_name='archive',
            name='original_text',
            field=models.TextField(default=''),
        ),
    ]
