# from django.test import TestCase

# Create your tests here.

from openai import OpenAI

submit_string = """
    I was looking for something, but then all this noise started distracting me. All of this has happened before, with me getting annoyed by the radio, then punching the dials and trying to turn the music off. The knobs are too greasy though. The oil from the deep fryer has literally sunk in to the system, and I say, “Wow. Literally sunken in.” And that’s when I realize I don’t ever want to be back here, in this office cluttered with paper and the smell of diesel, where the air is so thick I might be shot out of here like a champagne cork, even though no one is celebrating. Back to work, in this old, crusty gas station, I guess. And this music issue is one I’ll get to.
    I don’t want to work. I spam that phrase in my head every time I have a second to look around for my manager and to check the camera and make sure I’m enough out of view to look at my phone. That’s what I would normally do in this immediate aftermath, before anyone comes through that door and says, “yall serving breakfast?” and I get something fluttering in my head, something like compound deja vu, because this is an instance where I know, I know I’ve been here before. I know I worked on this stereo system about a hundred times. And I keep walking the same red line path, following the tiles between these store shelves, talking to myself about how I’m a writer with so much urge to get something out, so much artistic debt, so much umph inside me, and I’m almost waking up to that, but instead I’m taken over by the window.
    The light coming through is pure orange, hazy, and warming. So it must be exactly 7:30. I know this, because that’s when the sun starts casting an orange glow. I am alone in the shop right now. I could bask in this glow with quite the intention to just relax and think about the past twelve years of my life. I should appreciate these peaceful moments more, and maybe let them aide me when another customer asks for the trifecta of beer, cigarettes, and lottery tickets. And when he’s upset with me he jokes about wanting to take a finger. I can’t remember how that joke went, whether something about the finger was the setup or the punchline to a joke. I should remember that. This is a joke I heard many years ago, brought to me by a customer who handed me a newspaper and told me to read it, and I had no idea if I should let him command me like I’m a robot. But I read the joke and found it compulsively readable. The whole newspaper was enlightening, addictive, full of tales of fishermen off the coast. And I wanted to know who edited the paper, and I asked him, and this old man said, “Thomas.”
    That happened on one particular day, twelve years ago, the one and only day I have ever enjoyed work. Every other day is such a drag. The light is fading from the window now. The music is still driving me insane. And I don’t know how different it will be to stay awake all through the night, as the only worker in this shop. I go down to the basement, in an office lit by dull fluorescent light. This is where I sit in a chair with cracked, fake leather and watch the cameras, until well past the point where I know the sun out there has gone down—well, it hasn’t gone down, the earth has just turned away from it again—and the sky has gotten icy blue. That deep blue, so temporal and ethereal, and I think, right as I’m missing it, it could suck me into infinity. I have to do so much, but all of it is meaningless. I have to read these technical manuals packed into binders. I have to read e-mails on a computer that sill uses dial-up, pack boxes full of books, scan documents. I have nowhere near enough dopamine floating around in my head to find the motivation to get all this done. And there’s so many books in here I’d rather read, so many cell phones full of addictive games, and I have to remind myself constantly that I came here telling myself to be okay with boredom. Let the boredom build up and push me into doing something refreshing, or give me time to reflect on myself and remember who I am, remember what I’ve started. There’s a notebook somewhere around here, where I wrote down some advice, or some quotes, or some kind of to-do list full of adverbs, telling myself to write hastily, get your day started adamantly, don’t talk to yourself so frequently, don’t imagine yourself on the radio so delusionally, and now I’m thinking my god, my god, where is that damn notebook the one that I was able to settle into for a long period, for one day, and write seven full pages—fourteen pages, really, seven full spreads. I know where it is, but I stashed it very far way.
    The clock says it’s midnight, but then again I’m not even sure if that’s a clock. It has what looks like minute and hour hands, both stuck pointing straight up, like it’s stuck on midnight. I won’t tick either. So either it’s out of batteries or I’m in some kind of zone where time can’t move. That would make sense, as I haven’t seen anyone else in here for a while, and usually those neighborhood kids are knocking on the top part of those windows near the basement’s ceiling. I at least remember where I am, in that video game universe where all the gadgets and other material from my grandmother’s attic has been virtually loaded into this basement. All the aesthetics are the same, where everything is built with sturdy wood, and there’s old carpet. Some of this wood is rotted though. And I’ve forgotten why I came here, or if I’ll ever make it back out. I’ve been looking for my video game console this whole time, even though I don’t think it has ever been here.
    Seeking out my console has got to be the easiest kind of game. I can’t even win that. I only have the television here, and it’s showing streams. My first contact with another human, which proves to me that indeed the time is moving, that the laws of physics haven’t actually screwed up that badly, is the moment I turn on a 1970’s television, complete with the thick wooden frame and a single knob for changing the channels. The pixels are faded. The sound is murky. And this episode of Power Rangers is playing out exactly how I remember it. I do nothing but watch the television, because there’s no video game consoles here and definitely no internet. At night, when even the television signal goes out, I go to the window. I have a lingering feeling my parents and grandparents will want to watch Sixty Minutes soon, and they’ll pop some popcorn in that microwave that takes over five minutes to cook the bag. But that world is gone. Almost everything about that place has been looted from this house. Even the bushes full of bumble bees are gone. They’ve just left that worthless television and the one streetlight out in the front lawn. The one light that illuminates all the pine trees behind it, and the cars on the gravel lot. I’ve wondered since I was a kid how my grandmother and grandfather managed to get an actual streetlight put out here in their yard, and I still don’t know. They’ve never told me.
    And I’m looking down their driveway now, their half-mile driveway that any fourth-grade kid should desire. I’m only half a mile or less from where my very first experience with any video game console took place. I’ve looked for this exact spot since I could get into Google Maps. I’ve tried to track this place down through satellite imagery. And to be put back here, to be zapped back into this, that must mean I’ve got to go back there, and I don’t care if it’s dark; I’ll go. I open the door, and the windows beside it crack, as if they’re in a storm with strong winds. I don’t care. It must be night, but I don’t care. I’ll stay focused. The moon is shining just as brightly as that street light. This is perfect. I can head out, and I’ll ignore the dried up firewood that could make a perfect fire, or the tractor, the shed where there are feasibly two tractors. In the shed up ahead is where my uncle used to have almost all of his tools.
    And that’s all there is. There’s the big overhanging shed, with the two rooms attached to it, for him to do whatever. Why does he even have all this equipment? I don’t want to look through it. This place is too much of a mess. And I have no idea what any of this was used for. The only thing I might want to find is a sign that he’s been here recently, but that can’t be true, unless this really is a big gigantic game where anything can happen. Maybe I could find a single wire, the AV cables. Come to think of it, this one cord doesn’t plug into the drill, and if I trace it back, it seems loose. I can pull the end up, and sure enough, this is an AV cable.
    """

client = OpenAI()

stream = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a professional copy editor who fixes typos and grammatical mistakes in text. You follow MLA style for making corrections. You make MINIMAL edits to the voice or style of the prose, only correcting when there are obvious errors."},
        {"role": "user", "content": submit_string}],
        stream=True,
    )
for chunk in stream:
    if chunk.choices[0].delta.content is not None:
        print(chunk.choices[0].delta.content, end="")

print(stream)


if __name__ == "__main__":
    ...